/** @format */

import store from "@/store";
import {
  VuexModule,
  Module,
  Action,
  Mutation,
  getModule,
} from "vuex-module-decorators";

export interface IChia {
  province: any;
}

@Module({ dynamic: true, store, name: "ChianProvince" })
class ChianProvince extends VuexModule implements IChia {
  public province = [
    {
      name: "北京市",
      city: [
        "东城区",
        "西城区",
        "崇文区",
        "宣武区",
        "朝阳区",
        "海淀区",
        "丰台区",
        "石景山",
      ],
    },
    {
      name: "天津市",
      city: [
        "和平",
        "河北",
        "河西",
        "河东",
        "南开",
        "红桥",
        "塘沽",
        "汉沽",
        "大港",
        "东丽",
        "西青",
        "津南",
        "北辰",
        "武清",
        "滨海",
      ],
    },
    {
      name: "河北省",
      city: [
        "石家庄",
        "唐山",
        "秦皇岛",
        "邯郸",
        "邢台",
        "张家口",
        "承德",
        "廊坊",
        "沧州",
        "保定",
        "衡水",
      ],
    },
    {
      name: "山西省",
      city: ["太原", "大同", "阳泉", "朔州", "长治", "临汾", "晋城"],
    },
    {
      name: "内蒙古自治区",
      city: [
        "呼和浩特",
        "包头",
        "乌海",
        "临河",
        "东胜",
        "集宁",
        "锡林浩特",
        "通辽",
        "赤峰",
        "海拉尔",
        "乌兰浩特",
      ],
    },
    {
      name: "辽宁省",
      city: [
        "沈阳",
        "大连",
        "鞍山",
        "锦州",
        "丹东",
        "盘锦",
        "铁岭",
        "抚顺",
        "营口",
        "辽阳",
        "阜新",
        "本溪",
        "朝阳",
        "葫芦岛",
      ],
    },
    {
      name: "吉林省",
      city: [
        "长春",
        "吉林",
        "四平",
        "辽源",
        "通化",
        "白山",
        "松原",
        "白城",
        "延边",
      ],
    },
    {
      name: "黑龙江省",
      city: [
        "哈尔滨",
        "齐齐哈尔",
        "牡丹江",
        "佳木斯",
        "大庆",
        "伊春",
        "黑河",
        "鸡西",
        "鹤岗",
        "双鸭山",
        "七台河",
        "绥化",
        "大兴安岭",
      ],
    },
    {
      name: "上海市",
      city: [
        "宝山",
        "金山",
        "南市",
        "长宁",
        "静安",
        "青浦",
        "崇明",
        "卢湾",
        "松江",
        "奉贤",
        "浦东",
        "杨浦",
        "虹口",
        "普陀",
        "闸北",
        "黄浦",
        "闵行",
        "徐汇",
        "嘉定",
        "南汇",
      ],
    },
    {
      name: "江苏省",
      city: [
        "南京",
        "苏州",
        "无锡",
        "常州",
        "镇江",
        "连云港 ",
        "扬州",
        "徐州 ",
        "南通",
        "盐城",
        "淮阴",
        "泰州",
        "宿迁",
      ],
    },
    { name: "浙江省" },
    { name: "安徽省" },
    { name: "福建省" },
    { name: "江西省" },
    { name: "山东省" },
    { name: "河南省" },
    { name: "湖北省" },
    { name: "湖南省" },
    { name: "广东省" },
    { name: "广西壮族自治区" },
    { name: "海南省" },
    { name: "重庆市" },
    { name: "四川省" },
    { name: "贵州省" },
    { name: "云南省" },
    { name: "西藏自治区" },
    { name: "陕西省" },
    { name: "甘肃省" },
    { name: "青海省" },
    { name: "宁夏回族自治区" },
    { name: "新疆维吾尔自治区" },
    { name: "香港特别行政区" },
    { name: "澳门特别行政区" },
    { name: "台湾省" },
  ];
}

export const ChianProvinceModule = getModule(ChianProvince);
